[package]
name = "stockbasterd-rs"
version = "0.1.3"
edition = "2021"

[dependencies]
futures = "0.3.29"
tokio = { version = "1.33.0", features = ["full"] }

rfd = "0.12.1"
regex = "1.10.2"
dirs = "5.0.1"

reqwest = { version = "0.11.22", features = ["blocking"] }
scraper = "0.18.1"
