[package]
name = "stockbasterd-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.29"
tokio = { version = "1.33.0", features = ["full"] }

rfd = "0.12.1"
regex = "1.10.2"

reqwest = "0.11.22"
scraper = "0.18.1"
